//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace WeekEndingTabs {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(12)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class Sheet11 : Microsoft.Office.Tools.Excel.WorksheetBase {
        
        internal Microsoft.Office.Tools.Excel.NamedRange closingDay;
        
        internal Microsoft.Office.Tools.Excel.NamedRange datedSheets;
        
        internal Microsoft.Office.Tools.Excel.NamedRange datedSheetsFmt;
        
        internal Microsoft.Office.Tools.Excel.NamedRange dayDates;
        
        internal Microsoft.Office.Tools.Excel.NamedRange dayDatesRaw;
        
        internal Microsoft.Office.Tools.Excel.NamedRange daysOfWeek;
        
        internal Microsoft.Office.Tools.Excel.NamedRange daysOfWeekFmt;
        
        internal Microsoft.Office.Tools.Excel.NamedRange daysOfWeekRaw;
        
        internal Microsoft.Office.Tools.Excel.NamedRange lastDayOfWeek;
        
        internal Microsoft.Office.Tools.Excel.NamedRange prevWEDate;
        
        internal Microsoft.Office.Tools.Excel.NamedRange prevWEDaye;
        
        internal Microsoft.Office.Tools.Excel.NamedRange selectedDate;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Sheet11(global::Microsoft.Office.Tools.Excel.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "Sheet11", "Sheet11") {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            Globals.Sheet11 = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.closingDay.BeginInit();
            this.datedSheets.BeginInit();
            this.datedSheetsFmt.BeginInit();
            this.dayDates.BeginInit();
            this.dayDatesRaw.BeginInit();
            this.daysOfWeek.BeginInit();
            this.daysOfWeekFmt.BeginInit();
            this.daysOfWeekRaw.BeginInit();
            this.lastDayOfWeek.BeginInit();
            this.prevWEDate.BeginInit();
            this.prevWEDaye.BeginInit();
            this.selectedDate.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.selectedDate.EndInit();
            this.prevWEDaye.EndInit();
            this.prevWEDate.EndInit();
            this.lastDayOfWeek.EndInit();
            this.daysOfWeekRaw.EndInit();
            this.daysOfWeekFmt.EndInit();
            this.daysOfWeek.EndInit();
            this.dayDatesRaw.EndInit();
            this.dayDates.EndInit();
            this.datedSheetsFmt.EndInit();
            this.datedSheets.EndInit();
            this.closingDay.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.closingDay = Globals.Factory.CreateNamedRange(null, null, "closingDay", "closingDay", this);
            this.datedSheets = Globals.Factory.CreateNamedRange(null, null, "datedSheets", "datedSheets", this);
            this.datedSheetsFmt = Globals.Factory.CreateNamedRange(null, null, "datedSheetsFmt", "datedSheetsFmt", this);
            this.dayDates = Globals.Factory.CreateNamedRange(null, null, "dayDates", "dayDates", this);
            this.dayDatesRaw = Globals.Factory.CreateNamedRange(null, null, "dayDatesRaw", "dayDatesRaw", this);
            this.daysOfWeek = Globals.Factory.CreateNamedRange(null, null, "daysOfWeek", "daysOfWeek", this);
            this.daysOfWeekFmt = Globals.Factory.CreateNamedRange(null, null, "daysOfWeekFmt", "daysOfWeekFmt", this);
            this.daysOfWeekRaw = Globals.Factory.CreateNamedRange(null, null, "daysOfWeekRaw", "daysOfWeekRaw", this);
            this.lastDayOfWeek = Globals.Factory.CreateNamedRange(null, null, "lastDayOfWeek", "lastDayOfWeek", this);
            this.prevWEDate = Globals.Factory.CreateNamedRange(null, null, "prevWEDate", "prevWEDate", this);
            this.prevWEDaye = Globals.Factory.CreateNamedRange(null, null, "prevWEDaye", "prevWEDaye", this);
            this.selectedDate = Globals.Factory.CreateNamedRange(null, null, "selectedDate", "selectedDate", this);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.selectedDate.Dispose();
            this.prevWEDaye.Dispose();
            this.prevWEDate.Dispose();
            this.lastDayOfWeek.Dispose();
            this.daysOfWeekRaw.Dispose();
            this.daysOfWeekFmt.Dispose();
            this.daysOfWeek.Dispose();
            this.dayDatesRaw.Dispose();
            this.dayDates.Dispose();
            this.datedSheetsFmt.Dispose();
            this.datedSheets.Dispose();
            this.closingDay.Dispose();
            base.OnShutdown();
        }
    }
    
    internal sealed partial class Globals {
        
        private static Sheet11 _Sheet11;
        
        internal static Sheet11 Sheet11 {
            get {
                return _Sheet11;
            }
            set {
                if ((_Sheet11 == null)) {
                    _Sheet11 = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
    }
}
